### ISSUE TITLE
[2021-5-19] 伪元素和伪类的区别和作用是什么？

### ISSUE THREAD

**Issue by HJY-xh** [HJY-xh/plantTrees#252]

**Comment by HJY-xh** [comment]
-  伪元素：在内容元素的前后插入额外的元素或样式，但是这些元素实际上并不在文档中生成。它们只在外部显示可见，但不会在文档的源代码中找到它们，因此，称为“伪”元素。例如：
```css
p::before {content:"第一章：";}
p::after {content:"Hot!";}
p::first-line {background:red;}
p::first-letter {font-size:30px;}
```
- 伪类：将特殊的效果添加到特定选择器上。它是已有元素上添加类别的，不会产生新的元素。例如：
```css
a:hover {color: #FF00FF}
p:first-child {color: red}
```

总结：伪类是通过在元素选择器上加⼊伪类改变元素状态，⽽伪元素通过对元素的操作进⾏对元素的改变。
