### ISSUE TITLE
[2021-6-10] em和rem如何转换为像素值？

### ISSUE THREAD

**Issue by JaeWong-CN** [HJY-xh/plantTrees#294]

**Comment by JaeWong-CN** [comment]
- **em是如何转换成px的**
1. 当使用em单位时，像素值是将em值乘以使用em单位的元素的字体大小，例如一个div的字体为18px，设置它的宽高为10em，那么此时宽高就是18px * 10em = 180px。
```CSS
.test{
  width: 10em;
  height: 10em;
  background-color: #ff7d42;
  font-size: 18px;
}
```
一定要记住的是，em是根据使用它的元素的font-size的大小来变化的，而不是根据父元素字体大小，有些元素大小是父元素的多少倍是因为继承了父元素中font-size的设定

2. em单位的继承效果
使用em单位存在继承的时候，每个元素将自动继承其父元素的字体大小，继承的效果只能被明确的字体单位覆盖，比如px和vw，只要父级元素上面一直有font-size为em单位，则会一直继承，但假如自己设置了font-size的单位为px的时候，则会直接使用自己的px单位的值

- **rem是如何转换成px的**
当使用rem时，页面转换为像素大小取决于根元素的字体大小乘rem的值，即HTML元素的字体大小乘rem的值。例如，根元素的字体大小为16px，那么10rem就等同于10rem * 16px = 160px。
