### ISSUE TITLE
[2021-6-11] 如何解决iPhone和iPad下输入框默认内阴影？

### ISSUE THREAD

**Issue by JaeWong-CN** [HJY-xh/plantTrees#297]

**Comment by JaeWong-CN** [comment]
通过以下代码设置样式：
```css
element{
  -webkit-appearance: none;
}
```
