### ISSUE TITLE
[2021-6-11] 如何解决上下拖动滚动条时的卡顿问题？

### ISSUE THREAD

**Issue by JaeWong-CN** [HJY-xh/plantTrees#298]

**Comment by JaeWong-CN** [comment]
通过以下代码设置样式：
```css
body{
  -webkit-overflow-scrolling: touch;
  overflow-scrolling: touch;
}
```
**overflow-scrolling为CSS3新增属性，Android 3+ 和 iOS 5+ 支持。**
