### ISSUE TITLE
[2021-6-11] 如何解决移动端长时间按住页面出现闪退的问题

### ISSUE THREAD

**Issue by JaeWong-CN** [HJY-xh/plantTrees#299]

**Comment by JaeWong-CN** [comment]
通过以下代码设置样式：
```css
element{
  -webkit-touch-callout: none;
}
```
