### ISSUE TITLE
Textarea 如何禁止拉伸

### ISSUE THREAD

**Issue by HJY-xh** [HJY-xh/plantTrees#45]

**Comment by HJY-xh** [comment]
使用 CSS 样式可以避免拉伸:
```css
textarea {
  resize: none;
}
```
