### ISSUE TITLE
[2022-1-21] 左边定宽，右边⾃适应的布局有哪些写法？

### ISSUE THREAD

**Issue by HJY-xh** [HJY-xh/plantTrees#519]

**Comment by HJY-xh** [comment]
```css
// 方案1
.left {
  width: 120px;
  float: left;
}
.right {
  margin-left: 120px
}

// 方案2
.left {
  width: 120px;
  float: left;
}
.right {
  width: calc(100% - 120px);
  float: left;
}
```
