### ISSUE TITLE
[2022-2-14] Sass中混合指令@mixin 和 函数指令 @function 的区别?

### ISSUE THREAD

**Issue by HJY-xh** [HJY-xh/plantTrees#525]

**Comment by HJY-xh** [comment]
定义方式不同， @function 需要调用@return输出结果，而 @mixin 不需要:

```css
@mixin base-font ($value: 20px) {
  font-size: $value;
  color: #ff0000;
}

@function double($n) {
　　@return $n * 2;
}
```

@mixin 是需要 @include来引用，而且不需要小括号，而 @function 是使用需要小括号来执行的:

```css
 div {
   @include base-font;
   width: double(20px);
 }
```
